In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../datasets/mobility.csv")

In [3]:
df.head()

,Timestamp,Latitude,Longitude,Vehicle_Count,Traffic_Speed_kmh,Road_Occupancy_%,Traffic_Light_State,Weather_Condition,Accident_Report,Sentiment_Score,Ride_Sharing_Demand,Parking_Availability,Emission_Levels_g_km,Energy_Consumption_L_h,Traffic_Condition
0,2024-03-01 00:00:00,40.842275,-73.703149,205,49.893435,82.652780,Yellow,Clear,0,-0.609199,2,45,450.760055,19.574337,High
1,2024-03-01 00:05:00,40.831119,-73.987354,202,22.383965,45.829298,Green,Clear,0,0.965442,16,1,321.800341,5.385554,High
2,2024-03-01 00:10:00,40.819549,-73.732462,252,46.889699,82.772465,Green,Rain,0,0.289660,16,49,231.152655,10.277477,High
3,2024-03-01 00:15:00,40.725849,-73.980134,37,5.730536,37.695567,Red,Fog,0,-0.271965,66,10,410.384292,29.243279,High
4,2024-03-01 00:20:00,40.813265,-73.961631,64,61.348034,22.313358,Red,Snow,0,-0.797606,3,5,364.466342,16.801459,Low

In [4]:
df.tail()

,Timestamp,Latitude,Longitude,Vehicle_Count,Traffic_Speed_kmh,Road_Occupancy_%,Traffic_Light_State,Weather_Condition,Accident_Report,Sentiment_Score,Ride_Sharing_Demand,Parking_Availability,Emission_Levels_g_km,Energy_Consumption_L_h,Traffic_Condition
4995,2024-03-18 08:15:00,40.604663,-73.831032,266,22.987611,12.670629,Green,Rain,0,0.698929,87,28,252.070807,7.511153,High
4996,2024-03-18 08:20:00,40.733790,-73.752213,20,75.736987,49.108556,Green,Snow,0,0.742800,5,0,203.563872,6.681980,Low
4997,2024-03-18 08:25:00,40.821354,-73.759376,43,59.492981,78.719110,Yellow,Clear,0,0.524574,94,16,71.660296,25.267246,Medium
4998,2024-03-18 08:30:00,40.772343,-73.836698,88,25.901119,64.690719,Yellow,Rain,0,-0.589902,73,5,442.692618,29.467326,Medium
4999,2024-03-18 08:35:00,40.756688,-73.849335,147,51.473769,28.048376,Green,Snow,0,0.569793,93,16,119.196815,25.065909,Medium

In [5]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 5000
Columns : 15

In [6]:
df.columns.tolist()

['Timestamp',
 'Latitude',
 'Longitude',
 'Vehicle_Count',
 'Traffic_Speed_kmh',
 'Road_Occupancy_%',
 'Traffic_Light_State',
 'Weather_Condition',
 'Accident_Report',
 'Sentiment_Score',
 'Ride_Sharing_Demand',
 'Parking_Availability',
 'Emission_Levels_g_km',
 'Energy_Consumption_L_h',
 'Traffic_Condition']

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Latitude,5000.0,40.749645,0.086123,40.600016,40.675403,40.748875,40.824735,40.899972
Longitude,5000.0,-73.847433,0.086204,-73.999987,-73.920281,-73.846058,-73.771685,-73.700159
Vehicle_Count,5000.0,153.921200,83.523342,10.000000,80.000000,156.000000,226.000000,299.000000
Traffic_Speed_kmh,5000.0,42.111096,21.707720,5.002789,23.195752,42.191599,60.751760,79.997556
Road_Occupancy_%,5000.0,54.748397,26.145238,10.005031,32.089653,54.657297,77.581720,99.999729
Accident_Report,5000.0,0.096000,0.294621,0.000000,0.000000,0.000000,0.000000,1.000000
Sentiment_Score,5000.0,-0.005652,0.583790,-0.999819,-0.500154,-0.010564,0.500518,0.999354
Ride_Sharing_Demand,5000.0,50.487800,28.484426,1.000000,26.000000,50.000000,75.000000,99.000000
Parking_Availability,5000.0,24.613000,14.532511,0.000000,12.000000,24.000000,37.000000,49.000000
Emission_Levels_g_km,5000.0,272.174927,130.086372,50.136855,160.564433,272.045513,382.242055,499.922663
Energy_Consumption_L_h,5000.0,17.343243,7.208277,5.003787,11.098761,17.153791,23.516595,29.995416

In [8]:
df.isnull().sum()

Timestamp                 0
Latitude                  0
Longitude                 0
Vehicle_Count             0
Traffic_Speed_kmh         0
Road_Occupancy_%          0
Traffic_Light_State       0
Weather_Condition         0
Accident_Report           0
Sentiment_Score           0
Ride_Sharing_Demand       0
Parking_Availability      0
Emission_Levels_g_km      0
Energy_Consumption_L_h    0
Traffic_Condition         0
dtype: int64

In [9]:
(df.isnull().sum() / len(df)) * 100

Timestamp                 0.0
Latitude                  0.0
Longitude                 0.0
Vehicle_Count             0.0
Traffic_Speed_kmh         0.0
Road_Occupancy_%          0.0
Traffic_Light_State       0.0
Weather_Condition         0.0
Accident_Report           0.0
Sentiment_Score           0.0
Ride_Sharing_Demand       0.0
Parking_Availability      0.0
Emission_Levels_g_km      0.0
Energy_Consumption_L_h    0.0
Traffic_Condition         0.0
dtype: float64

In [10]:
print("Duplicate Rows :", df.duplicated().sum())

Duplicate Rows : 0

In [11]:
df = df.drop_duplicates()

print(df.shape)

(5000, 15)

In [12]:
df.dtypes

Timestamp                     str
Latitude                  float64
Longitude                 float64
Vehicle_Count               int64
Traffic_Speed_kmh         float64
Road_Occupancy_%          float64
Traffic_Light_State           str
Weather_Condition             str
Accident_Report             int64
Sentiment_Score           float64
Ride_Sharing_Demand         int64
Parking_Availability        int64
Emission_Levels_g_km      float64
Energy_Consumption_L_h    float64
Traffic_Condition             str
dtype: object

In [13]:
df.dtypes

Timestamp                     str
Latitude                  float64
Longitude                 float64
Vehicle_Count               int64
Traffic_Speed_kmh         float64
Road_Occupancy_%          float64
Traffic_Light_State           str
Weather_Condition             str
Accident_Report             int64
Sentiment_Score           float64
Ride_Sharing_Demand         int64
Parking_Availability        int64
Emission_Levels_g_km      float64
Energy_Consumption_L_h    float64
Traffic_Condition             str
dtype: object

In [14]:
df.select_dtypes(include=["number"]).columns

Index(['Latitude', 'Longitude', 'Vehicle_Count', 'Traffic_Speed_kmh',
       'Road_Occupancy_%', 'Accident_Report', 'Sentiment_Score',
       'Ride_Sharing_Demand', 'Parking_Availability', 'Emission_Levels_g_km',
       'Energy_Consumption_L_h'],
      dtype='str')

In [15]:
df.select_dtypes(include=["object"]).columns

C:\Users\DELL\AppData\Local\Temp\ipykernel_19244\2790643224.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=["object"]).columns

Index(['Timestamp', 'Traffic_Light_State', 'Weather_Condition',
       'Traffic_Condition'],
      dtype='str')

In [16]:
df.nunique()

Timestamp                 5000
Latitude                  5000
Longitude                 5000
Vehicle_Count              290
Traffic_Speed_kmh         5000
Road_Occupancy_%          5000
Traffic_Light_State          3
Weather_Condition            4
Accident_Report              2
Sentiment_Score           5000
Ride_Sharing_Demand         99
Parking_Availability        50
Emission_Levels_g_km      5000
Energy_Consumption_L_h    5000
Traffic_Condition            3
dtype: int64

In [17]:
df.to_csv("../cleaned_data/mobility_cleaned.csv", index=False)

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Timestamp               5000 non-null   str
 1   Latitude                5000 non-null   float64
 2   Longitude               5000 non-null   float64
 3   Vehicle_Count           5000 non-null   int64
 4   Traffic_Speed_kmh       5000 non-null   float64
 5   Road_Occupancy_%        5000 non-null   float64
 6   Traffic_Light_State     5000 non-null   str
 7   Weather_Condition       5000 non-null   str
 8   Accident_Report         5000 non-null   int64
 9   Sentiment_Score         5000 non-null   float64
 10  Ride_Sharing_Demand     5000 non-null   int64
 11  Parking_Availability    5000 non-null   int64
 12  Emission_Levels_g_km    5000 non-null   float64
 13  Energy_Consumption_L_h  5000 non-null   float64
 14  Traffic_Condition       5000 non-null   str
dtypes: float64(7), int64(4), str(4)
memory usage: 586.1 KB

In [19]:
df.columns.tolist()

['Timestamp',
 'Latitude',
 'Longitude',
 'Vehicle_Count',
 'Traffic_Speed_kmh',
 'Road_Occupancy_%',
 'Traffic_Light_State',
 'Weather_Condition',
 'Accident_Report',
 'Sentiment_Score',
 'Ride_Sharing_Demand',
 'Parking_Availability',
 'Emission_Levels_g_km',
 'Energy_Consumption_L_h',
 'Traffic_Condition']

In [20]:
df.isnull().sum()

Timestamp                 0
Latitude                  0
Longitude                 0
Vehicle_Count             0
Traffic_Speed_kmh         0
Road_Occupancy_%          0
Traffic_Light_State       0
Weather_Condition         0
Accident_Report           0
Sentiment_Score           0
Ride_Sharing_Demand       0
Parking_Availability      0
Emission_Levels_g_km      0
Energy_Consumption_L_h    0
Traffic_Condition         0
dtype: int64

In [21]:
print(df.duplicated().sum())

0

In [22]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Timestamp               5000 non-null   datetime64[us]
 1   Latitude                5000 non-null   float64
 2   Longitude               5000 non-null   float64
 3   Vehicle_Count           5000 non-null   int64
 4   Traffic_Speed_kmh       5000 non-null   float64
 5   Road_Occupancy_%        5000 non-null   float64
 6   Traffic_Light_State     5000 non-null   str
 7   Weather_Condition       5000 non-null   str
 8   Accident_Report         5000 non-null   int64
 9   Sentiment_Score         5000 non-null   float64
 10  Ride_Sharing_Demand     5000 non-null   int64
 11  Parking_Availability    5000 non-null   int64
 12  Emission_Levels_g_km    5000 non-null   float64
 13  Energy_Consumption_L_h  5000 non-null   float64
 14  Traffic_Condition       5000 non-null   str
dtypes: datetime64[us](1), float64(7), int64(4), str(3)
memory usage: 586.1 KB

In [24]:
df["Hour"] = df["Timestamp"].dt.hour
df["Day"] = df["Timestamp"].dt.day
df["Month"] = df["Timestamp"].dt.month
df["Weekday"] = df["Timestamp"].dt.day_name()

In [25]:
df.head()

,Timestamp,Latitude,Longitude,Vehicle_Count,Traffic_Speed_kmh,Road_Occupancy_%,Traffic_Light_State,Weather_Condition,Accident_Report,Sentiment_Score,Ride_Sharing_Demand,Parking_Availability,Emission_Levels_g_km,Energy_Consumption_L_h,Traffic_Condition,Hour,Day,Month,Weekday
0,2024-03-01 00:00:00,40.842275,-73.703149,205,49.893435,82.652780,Yellow,Clear,0,-0.609199,2,45,450.760055,19.574337,High,0,1,3,Friday
1,2024-03-01 00:05:00,40.831119,-73.987354,202,22.383965,45.829298,Green,Clear,0,0.965442,16,1,321.800341,5.385554,High,0,1,3,Friday
2,2024-03-01 00:10:00,40.819549,-73.732462,252,46.889699,82.772465,Green,Rain,0,0.289660,16,49,231.152655,10.277477,High,0,1,3,Friday
3,2024-03-01 00:15:00,40.725849,-73.980134,37,5.730536,37.695567,Red,Fog,0,-0.271965,66,10,410.384292,29.243279,High,0,1,3,Friday
4,2024-03-01 00:20:00,40.813265,-73.961631,64,61.348034,22.313358,Red,Snow,0,-0.797606,3,5,364.466342,16.801459,Low,0,1,3,Friday

In [26]:
df["Traffic_Condition"].value_counts()

Traffic_Condition
High      3166
Medium    1475
Low        359
Name: count, dtype: int64